# Generated by Django 5.0.1 on 2026-01-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20260115_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('TR', 'Tournament Rules'), ('CR', 'Comprehensive Rules')], max_length=2)),
                ('section', models.CharField(db_index=True, max_length=50)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='post.rulesection')),
            ],
            options={
                'ordering': ['rule_type', 'order', 'section'],
                'indexes': [models.Index(fields=['rule_type', 'section'], name='post_rulese_rule_ty_14598b_idx'), models.Index(fields=['parent', 'order'], name='post_rulese_parent__aae54a_idx')],
                'unique_together': {('rule_type', 'section')},
            },
        ),
    ]
