# Generated by Django 5.0.1 on 2026-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rulesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesection',
            name='annotations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
