# Generated by Django 6.0.1 on 2026-01-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rulesection_annotations'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Chaos', 'Chaos'), ('Order', 'Order'), ('Fury', 'Fury'), ('Calm', 'Calm'), ('Mind', 'Mind'), ('Body', 'Body'), ('Colorless', 'Colorless')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('collector_number', models.IntegerField()),
                ('energy', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('card_type', models.CharField(choices=[('Legend', 'Legend'), ('Spell', 'Spell'), ('Unit', 'Unit'), ('Rune', 'Rune'), ('Gear', 'Gear'), ('Battlefield', 'Battlefield')], default='Unit', max_length=20)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Showcase', 'Showcase')], default='Common', max_length=20)),
                ('card_set', models.CharField(choices=[('Origins', 'Origins'), ('Spiritforged', 'Spiritforged'), ('Proving Grounds', 'Proving Grounds')], default='Origins', max_length=20)),
                ('image_url', models.URLField()),
                ('ability', models.TextField(blank=True, default='')),
                ('errata_text', models.TextField(blank=True, null=True)),
                ('errata_old_text', models.TextField(blank=True, null=True)),
                ('domain', models.ManyToManyField(blank=True, related_name='cards', to='post.carddomain')),
            ],
            options={
                'ordering': ['card_set', 'collector_number'],
            },
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
