# Generated by Django 6.0.1 on 2026-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_carddomain_alter_post_tag_card_delete_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(choices=[('Origins', 'Origins'), ('Spiritforged', 'Spiritforged'), ('Proving Grounds', 'Proving Grounds'), ('Unleashed', 'Unleashed')], default='Origins', max_length=20),
        ),
    ]
