# Generated by Django 6.0.1 on 2026-05-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_card_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='gear_effect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='might_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
