# Generated by Django 5.1.15 on 2026-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_card_gear_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(choices=[('Origins', 'Origins'), ('Spiritforged', 'Spiritforged'), ('Proving Grounds', 'Proving Grounds'), ('Unleashed', 'Unleashed'), ('Vendetta', 'Vendetta')], default='Origins', max_length=20),
        ),
    ]
